#  Copyright 2022 - Offen Authors <hioffen@posteo.de>
#  SPDX-License-Identifier: Apache-2.0

version: '3'

services:
  proxy:
    image: caddy:2.5.1-alpine
    volumes:
      - ./dev/index.html:/var/www/html/index.html
      - ./dev/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 9001:9001

  server:
    build:
      context: '.'
      dockerfile: ./dev/Dockerfile
    working_dir: /code/server
    environment:
      DEVELOPMENT: 'true'
    ports:
      - 9000:9000
    volumes:
      - .:/code
      - serverdeps:/go/pkg
      - servercache:/data
    command: refresh run

volumes:
  serverdeps:
  servercache:
