version: 2.1

jobs:
  test_go:
    docker:
      - image: cimg/go:1.18
    working_directory: ~/consent
    steps:
      - checkout:
          path: ~/consent
      - run:
          name: Run tests
          command: go test -v ./...

  test_js:
    docker:
      - image: cimg/node:14.19
    working_directory: ~/consent
    steps:
      - checkout:
          path: ~/consent
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Run tests
          command: npm t

  release:
    docker:
      - image: cimg/go:1.18
    environment:
      DOCKER_LOGIN: offen
      DOCKER_BUILDKIT: '1'
      DOCKER_CLI_EXPERIMENTAL: enabled
    working_directory: ~/consent
    steps:
      - checkout:
          path: ~/consent
      - setup_remote_docker:
          version: 20.10.6
      - run:
          name: Build binaries
          command: make
      - run:
          name: Build Docker image
          command: |
            docker run --rm --privileged linuxkit/binfmt:v0.8
            echo "$DOCKER_ACCESSTOKEN" | docker login --username $DOCKER_LOGIN --password-stdin
            docker buildx build \
              --platform linux/amd64,linux/arm64,linux/arm/v7 \
              -t offen/consent:latest -t offen/consent:$CIRCLE_TAG \
              . --push
      - store_artifacts:
          path: ~/consent/bin

workflows:
  version: 2
  continuous_integration:
    jobs:
      - test_go: &default_filters
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - test_js: *default_filters
      - release:
          requires:
            - test_go
            - test_js
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+(-.+)?$/ # tagged release from any branch
            branches:
              ignore: /.*/
